// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	v1 "github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/types"
)

type FakeImage struct {
	ConfigFileStub        func() (*v1.ConfigFile, error)
	configFileMutex       sync.RWMutex
	configFileArgsForCall []struct {
	}
	configFileReturns struct {
		result1 *v1.ConfigFile
		result2 error
	}
	configFileReturnsOnCall map[int]struct {
		result1 *v1.ConfigFile
		result2 error
	}
	ConfigNameStub        func() (v1.Hash, error)
	configNameMutex       sync.RWMutex
	configNameArgsForCall []struct {
	}
	configNameReturns struct {
		result1 v1.Hash
		result2 error
	}
	configNameReturnsOnCall map[int]struct {
		result1 v1.Hash
		result2 error
	}
	DigestStub        func() (v1.Hash, error)
	digestMutex       sync.RWMutex
	digestArgsForCall []struct {
	}
	digestReturns struct {
		result1 v1.Hash
		result2 error
	}
	digestReturnsOnCall map[int]struct {
		result1 v1.Hash
		result2 error
	}
	LayerByDiffIDStub        func(v1.Hash) (v1.Layer, error)
	layerByDiffIDMutex       sync.RWMutex
	layerByDiffIDArgsForCall []struct {
		arg1 v1.Hash
	}
	layerByDiffIDReturns struct {
		result1 v1.Layer
		result2 error
	}
	layerByDiffIDReturnsOnCall map[int]struct {
		result1 v1.Layer
		result2 error
	}
	LayerByDigestStub        func(v1.Hash) (v1.Layer, error)
	layerByDigestMutex       sync.RWMutex
	layerByDigestArgsForCall []struct {
		arg1 v1.Hash
	}
	layerByDigestReturns struct {
		result1 v1.Layer
		result2 error
	}
	layerByDigestReturnsOnCall map[int]struct {
		result1 v1.Layer
		result2 error
	}
	LayersStub        func() ([]v1.Layer, error)
	layersMutex       sync.RWMutex
	layersArgsForCall []struct {
	}
	layersReturns struct {
		result1 []v1.Layer
		result2 error
	}
	layersReturnsOnCall map[int]struct {
		result1 []v1.Layer
		result2 error
	}
	ManifestStub        func() (*v1.Manifest, error)
	manifestMutex       sync.RWMutex
	manifestArgsForCall []struct {
	}
	manifestReturns struct {
		result1 *v1.Manifest
		result2 error
	}
	manifestReturnsOnCall map[int]struct {
		result1 *v1.Manifest
		result2 error
	}
	MediaTypeStub        func() (types.MediaType, error)
	mediaTypeMutex       sync.RWMutex
	mediaTypeArgsForCall []struct {
	}
	mediaTypeReturns struct {
		result1 types.MediaType
		result2 error
	}
	mediaTypeReturnsOnCall map[int]struct {
		result1 types.MediaType
		result2 error
	}
	RawConfigFileStub        func() ([]byte, error)
	rawConfigFileMutex       sync.RWMutex
	rawConfigFileArgsForCall []struct {
	}
	rawConfigFileReturns struct {
		result1 []byte
		result2 error
	}
	rawConfigFileReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	RawManifestStub        func() ([]byte, error)
	rawManifestMutex       sync.RWMutex
	rawManifestArgsForCall []struct {
	}
	rawManifestReturns struct {
		result1 []byte
		result2 error
	}
	rawManifestReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SizeStub        func() (int64, error)
	sizeMutex       sync.RWMutex
	sizeArgsForCall []struct {
	}
	sizeReturns struct {
		result1 int64
		result2 error
	}
	sizeReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImage) ConfigFile() (*v1.ConfigFile, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (fake *FakeImage) ConfigFileCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) ConfigFileCalls(stub func() (*v1.ConfigFile, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ConfigFileReturns(result1 *v1.ConfigFile, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ConfigFileReturnsOnCall(i int, result1 *v1.ConfigFile, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ConfigName() (v1.Hash, error) {
	_ = "STUB: not implemented"
	return *new(v1.Hash), nil
}

func (fake *FakeImage) ConfigNameCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) ConfigNameCalls(stub func() (v1.Hash, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ConfigNameReturns(result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ConfigNameReturnsOnCall(i int, result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) Digest() (v1.Hash, error) {
	_ = "STUB: not implemented"
	return *new(v1.Hash), nil
}

func (fake *FakeImage) DigestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) DigestCalls(stub func() (v1.Hash, error)) { _ = "STUB: not implemented"; return }

func (fake *FakeImage) DigestReturns(result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) DigestReturnsOnCall(i int, result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDiffID(arg1 v1.Hash) (v1.Layer, error) {
	_ = "STUB: not implemented"
	return *new(v1.Layer), nil
}

func (fake *FakeImage) LayerByDiffIDCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) LayerByDiffIDCalls(stub func(v1.Hash) (v1.Layer, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDiffIDArgsForCall(i int) v1.Hash {
	_ = "STUB: not implemented"
	return *new(v1.Hash)
}

func (fake *FakeImage) LayerByDiffIDReturns(result1 v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDiffIDReturnsOnCall(i int, result1 v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDigest(arg1 v1.Hash) (v1.Layer, error) {
	_ = "STUB: not implemented"
	return *new(v1.Layer), nil
}

func (fake *FakeImage) LayerByDigestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) LayerByDigestCalls(stub func(v1.Hash) (v1.Layer, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDigestArgsForCall(i int) v1.Hash {
	_ = "STUB: not implemented"
	return *new(v1.Hash)
}

func (fake *FakeImage) LayerByDigestReturns(result1 v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayerByDigestReturnsOnCall(i int, result1 v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) Layers() ([]v1.Layer, error) { _ = "STUB: not implemented"; return nil, nil }

func (fake *FakeImage) LayersCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) LayersCalls(stub func() ([]v1.Layer, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayersReturns(result1 []v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) LayersReturnsOnCall(i int, result1 []v1.Layer, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) Manifest() (*v1.Manifest, error) { _ = "STUB: not implemented"; return nil, nil }

func (fake *FakeImage) ManifestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) ManifestCalls(stub func() (*v1.Manifest, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ManifestReturns(result1 *v1.Manifest, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) ManifestReturnsOnCall(i int, result1 *v1.Manifest, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) MediaType() (types.MediaType, error) {
	_ = "STUB: not implemented"
	return *new(types.MediaType), nil
}

func (fake *FakeImage) MediaTypeCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) MediaTypeCalls(stub func() (types.MediaType, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) MediaTypeReturns(result1 types.MediaType, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) MediaTypeReturnsOnCall(i int, result1 types.MediaType, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawConfigFile() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (fake *FakeImage) RawConfigFileCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) RawConfigFileCalls(stub func() ([]byte, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawConfigFileReturns(result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawConfigFileReturnsOnCall(i int, result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawManifest() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (fake *FakeImage) RawManifestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) RawManifestCalls(stub func() ([]byte, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawManifestReturns(result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) RawManifestReturnsOnCall(i int, result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) Size() (int64, error) { _ = "STUB: not implemented"; return 0, nil }

func (fake *FakeImage) SizeCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImage) SizeCalls(stub func() (int64, error)) { _ = "STUB: not implemented"; return }

func (fake *FakeImage) SizeReturns(result1 int64, result2 error) { _ = "STUB: not implemented"; return }

func (fake *FakeImage) SizeReturnsOnCall(i int, result1 int64, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImage) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeImage) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ v1.Image = new(FakeImage)
