// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	v1 "github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/types"
)

type FakeImageIndex struct {
	DigestStub        func() (v1.Hash, error)
	digestMutex       sync.RWMutex
	digestArgsForCall []struct {
	}
	digestReturns struct {
		result1 v1.Hash
		result2 error
	}
	digestReturnsOnCall map[int]struct {
		result1 v1.Hash
		result2 error
	}
	ImageStub        func(v1.Hash) (v1.Image, error)
	imageMutex       sync.RWMutex
	imageArgsForCall []struct {
		arg1 v1.Hash
	}
	imageReturns struct {
		result1 v1.Image
		result2 error
	}
	imageReturnsOnCall map[int]struct {
		result1 v1.Image
		result2 error
	}
	ImageIndexStub        func(v1.Hash) (v1.ImageIndex, error)
	imageIndexMutex       sync.RWMutex
	imageIndexArgsForCall []struct {
		arg1 v1.Hash
	}
	imageIndexReturns struct {
		result1 v1.ImageIndex
		result2 error
	}
	imageIndexReturnsOnCall map[int]struct {
		result1 v1.ImageIndex
		result2 error
	}
	IndexManifestStub        func() (*v1.IndexManifest, error)
	indexManifestMutex       sync.RWMutex
	indexManifestArgsForCall []struct {
	}
	indexManifestReturns struct {
		result1 *v1.IndexManifest
		result2 error
	}
	indexManifestReturnsOnCall map[int]struct {
		result1 *v1.IndexManifest
		result2 error
	}
	MediaTypeStub        func() (types.MediaType, error)
	mediaTypeMutex       sync.RWMutex
	mediaTypeArgsForCall []struct {
	}
	mediaTypeReturns struct {
		result1 types.MediaType
		result2 error
	}
	mediaTypeReturnsOnCall map[int]struct {
		result1 types.MediaType
		result2 error
	}
	RawManifestStub        func() ([]byte, error)
	rawManifestMutex       sync.RWMutex
	rawManifestArgsForCall []struct {
	}
	rawManifestReturns struct {
		result1 []byte
		result2 error
	}
	rawManifestReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SizeStub        func() (int64, error)
	sizeMutex       sync.RWMutex
	sizeArgsForCall []struct {
	}
	sizeReturns struct {
		result1 int64
		result2 error
	}
	sizeReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImageIndex) Digest() (v1.Hash, error) {
	_ = "STUB: not implemented"
	return *new(v1.Hash), nil
}

func (fake *FakeImageIndex) DigestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) DigestCalls(stub func() (v1.Hash, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) DigestReturns(result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) DigestReturnsOnCall(i int, result1 v1.Hash, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) Image(arg1 v1.Hash) (v1.Image, error) {
	_ = "STUB: not implemented"
	return *new(v1.Image), nil
}

func (fake *FakeImageIndex) ImageCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) ImageCalls(stub func(v1.Hash) (v1.Image, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) ImageArgsForCall(i int) v1.Hash {
	_ = "STUB: not implemented"
	return *new(v1.Hash)
}

func (fake *FakeImageIndex) ImageReturns(result1 v1.Image, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) ImageReturnsOnCall(i int, result1 v1.Image, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) ImageIndex(arg1 v1.Hash) (v1.ImageIndex, error) {
	_ = "STUB: not implemented"
	return *new(v1.ImageIndex), nil
}

func (fake *FakeImageIndex) ImageIndexCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) ImageIndexCalls(stub func(v1.Hash) (v1.ImageIndex, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) ImageIndexArgsForCall(i int) v1.Hash {
	_ = "STUB: not implemented"
	return *new(v1.Hash)
}

func (fake *FakeImageIndex) ImageIndexReturns(result1 v1.ImageIndex, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) ImageIndexReturnsOnCall(i int, result1 v1.ImageIndex, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) IndexManifest() (*v1.IndexManifest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (fake *FakeImageIndex) IndexManifestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) IndexManifestCalls(stub func() (*v1.IndexManifest, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) IndexManifestReturns(result1 *v1.IndexManifest, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) IndexManifestReturnsOnCall(i int, result1 *v1.IndexManifest, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) MediaType() (types.MediaType, error) {
	_ = "STUB: not implemented"
	return *new(types.MediaType), nil
}

func (fake *FakeImageIndex) MediaTypeCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) MediaTypeCalls(stub func() (types.MediaType, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) MediaTypeReturns(result1 types.MediaType, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) MediaTypeReturnsOnCall(i int, result1 types.MediaType, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) RawManifest() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (fake *FakeImageIndex) RawManifestCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) RawManifestCalls(stub func() ([]byte, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) RawManifestReturns(result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) RawManifestReturnsOnCall(i int, result1 []byte, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) Size() (int64, error) { _ = "STUB: not implemented"; return 0, nil }

func (fake *FakeImageIndex) SizeCallCount() int { _ = "STUB: not implemented"; return 0 }

func (fake *FakeImageIndex) SizeCalls(stub func() (int64, error)) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) SizeReturns(result1 int64, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) SizeReturnsOnCall(i int, result1 int64, result2 error) {
	_ = "STUB: not implemented"
	return
}

func (fake *FakeImageIndex) Invocations() map[string][][]interface{} {
	_ = "STUB: not implemented"
	return nil
}

func (fake *FakeImageIndex) recordInvocation(key string, args []interface{}) {
	_ = "STUB: not implemented"
	return
}

var _ v1.ImageIndex = new(FakeImageIndex)
